developer-challenge/pgs-study

- hojin/lv2/42582 다리를 지나는 트럭.js
https://school.programmers.co.kr/learn/courses/30/lessons/42583
closes #2
Queue 자료구조를 통한 문제 풀이. 시간을 기준으로 자동차의 위치를 확인하며 구현할 수도 있겠지만, 시간을 장담할 수 없어서 각 트럭별로 들어온 시간과 나오는 시간을 체크하는 로직을 통해서 해결했습니다.  
Queue를 상속 받은 Bridge를 통해 
1. i번째 truck이 바로 Bridge에 입장 가능한 경우는 바로 넣어준다.
2. limit 무게보다 커서 들어올 수 없는 경우  
2.1 들어갈 수 있을 때까지는 가장 앞에 있는 head truck의 시간에 다리 길이만큼을 더한 퇴장 시간  
2.2 들어갈 수 있을 때 해당 시간과 함께 bridge queue에 넣어준다.
- Brige의 method 구현이 중요했고, 시간 check 로직도 중요했음.
> [HojinAn] lv.2 / 42583. 다리를 지나는 트럭 / 큐

- sangtae/lv2/12981 영어 끝말잇기.java
https://school.programmers.co.kr/learn/courses/30/lessons/12981
🔗 linked issue https://github.com/developer-challenge/pgs-study/issues/5
알고리즘 & 풀이 설명
n은 2 이상이므로 제일 앞 word 마지막 문자를 저장하고
모든 words를 확인하면서 제일 앞 문자와 일치하지 않거나 중간에 겹쳤던 word가 있으면
그 위치에서 나머지 연산과 갯수 세기로 탈락하는 사람과 몇 번째인지 구한다
boolean flag로 틀린 사람이 있는지 체크하여 없으면 {0,0} return
> [sangtae365] lv.2 / 12981. 영어 끝말잇기

- bori/lv1/159994.js
https://school.programmers.co.kr/learn/courses/30/lessons/159994
- for문을 돌면서 goal 배열도 shift를 하다가 해멨다.
> 문제 풀면서 어떤 문제가 있었는지에 대해 작성했습니다
- 현재 반복을 종료시키고 다음 반복으로 넘어가고 싶을 때 사용
- `for`, `for..of` 문에서는 `continue`를 사용할 수 있으나 `forEach` 문에서는 사용할 수 없다.
> [Bori-github] lv.1 / 159994. 카드뭉치 / practice

- bori/lv1/134240.js
- #7 
<br />
- 문자열을 주어진 횟수만큼 반복해 붙인 새로운 문자열 반환
```
// Syntax
str.repeat(count);
```
- `count` : 문자열을 반복할 횟수(0과 양의 무한대 사이의 정수)
> [Bori-github] lv.1 / 159994. 푸드 파이트 대회 / practice

- hojin/lv3/42579 베스트앨범.js
- #1
<br />
- Map을 이용한 간단한 풀이
- 더 JS스럽게 풀면 좋겠지만, 더 보기 좋게 푸는게 중요하다 생각
> [HojinAn] lv.3/42579/해시

- jiseung/bj/17404.RGB거리2.js
> [jiseung-kang] Gold.IV/17404/DP #13

- jiseung/bj/14002.js
- Closes #13 
<br />
- LIS
- 배열의 뒤에서부터 찾아야 올바르게 증가하는 수열을 찾을 수 있음
> [jiseung-kang] Gold.IV/14002/DP #13

- .idea/.gitignore
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- pgs-study.iml
- sangtae/lv2/P12980_점프와순간이동.java
dp로는 메모리 초과
- #5 
<br />
- 10억 이상의 숫자였기 때문에 dp말고 수학으로 풀었습니다.
> :sparkles: [sangtae365] lv2 / 12980. 점프와 순간 이동 / 수학

- sangtae/lv2/P12985_예상대진표.java
수학적인 접근
- #17 
<br />
- 1,2 / 3,4 /... / n-1, n 이런식으로 서로 승부하고 n이 2의 n승으로 이루어져 있어 
- 이겼을 경우 홀수는 2로 나누어 1을 더한 값이 되고
- 짝수는 2로 나눈 값이 된다
- 따라서 a, b를 같아질때까지 나누어 같으면 while문을 멈추게 하면 그것이 정답이다.
> :sparkles: [sangtae365] lv2 / 12985. 예상 대진표 / 수학,구현

- jiseung/lv3/118667.두 큐 합 같게 만들기.js
> [jiseung-kang] lv.3/118667/Two-Pointer #19

- sangtae/lv2/B1644_소수의연속합.java
수학, 투포인터 공부에 효율적
- #17 
<br />
- 프로그래머스를 풀어야 하는데 백준으로 올려서 죄송합니다.. ㅎㅎ
- 소수 구하는 방법과 투 포인터 공부에 좋은 문제라 풀어보았습니다.
- 소수의 배수를 빼면 소수만 남는다는 에라토스테네스의 체로 소수를 구하여 푸는 문제
> :sparkles: [sangtae365] gold3 / 1644. 소수의연속합 / 에라토스테네스의 체,투포인터

- hojin/lv2/42839 소수 찾기.js
- #23
<br />
- 단순 수학 구현 문제, 완전 탐색으로 해결했습니다.
> [HojinAn] lv.2/42839/수학&구현

- hojin/lv3/12979 기지국 설치.js
- #23
<br />
- 처음에 BFS로 접근했다가 잘못된 논리임을 깨닫고, 아이디어만 살짝 참고
- 각 기지국 별로 닿지 않는 범위를 계산해서 범위에 필요한 개수만큼 세어준다.
> [HojinAn] lv.3/12979/수학&구현

- hojin/lv2/68936. 쿼드압축 후 개수 세기.js
- #23
<br />
- 전형적인 분할 정복 문제
- 오랜만에 풀기도 하고 분할정복은 항상 까다롭다.
> [HojinAn] lv.2/68936/분할정복

- .idea/.gitignore
- sangtae/.idea/.gitignore
- sangtae/lv2/P138476_귤고르기.java
Hashmap getOrDefault 메서드 이해해서 좋았음
- #24 
<br />
- HashMap을 이용하여 독립된 숫자들의 갯수를 세어 set 말고 map을 이용하는 방법
> :sparkles: [sangtae365] lv2 / 138476. 귤 고르기 / 해시, 구현

- .idea/.gitignore
- sangtae/.idea/.gitignore
- sangtae/lv2/P42578_위장.java
모든 경우의 수 구할 때 (a+1)*(b+1)
- #24 
<br />
- 하나의 의상 종류가 2개가 있다고 하면 경우의 수는 
- 1. 안입는다 2. 종류1번 입는다 3. 종류2번 입는다
- 3가지가 되므로 각각 종류별로 가지수를 1씩 더하여 모든 경우의 수를 구한다
- 해시의 경우 HashMap getOrDefault 메서드를 이용했다
> :sparkles: [sangtae365] lv.2 / 42578. 위장 / 해시,수학

- jiseung/lv2/12914.js
> [jiseung-kang]  lv2 / 12914. 멀리뛰기 / math

- jiseung/lv2/138476.js
> [jiseung-kang] lv2 / 138476. 귤 고르기 / 해시, 구현

- sangtae/lv2/P64065_튜플.java
stream을 써서 list에서 배열로 바꾸는것을 처음 경험
- #34 
<br />
- 문자열 split, substring, replace로 숫자들을 빼내
- 길이를 비교하여 정렬하고
- 순서대로 list에 넣고 다음 것을 확인할 때 중복체크를 해주고 list에 넣는다
- 마지막으로 stream을 이용하여 list를 배열로 변환
> :sparkles: [sangtae365] lv2 / 64065. 튜플 / 문자열, 구현

- jiseung/lv2/42883 큰 수 만들기.js
> [jiseung] lv2 / 42883. 큰 수 만들기/그리디

- jiseung/lv2/42885 구명보트.js
> [jiseung] lv2 / 42885. 구명보트/그리디

- jiseung/lv3/42579. 베스트앨범.js
> [jiseung] lv3 / 42579. 베스트앨범/해시
